name: build

on: push

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        exclude:
          - os: macos-latest
            node-version: 12.x

    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Chad
        MIDDLE_NAME: Michael
        LAST_NAME: Crowell
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
